apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
   - nodePort: 30442 
     protocol: TCP
     port: 80
     targetPort: 80
     
  selector:
    app: nginx
  type: NodePort