---

apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: default
spec:
  ports:
   - nodePort: 30441 
     protocol: TCP
     port: 3000
     targetPort: 3000
     
  selector:
    app: node
  type: NodePort